from __future__ import annotations

from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.deps import get_current_user
from app.db.session import get_db
from app.models.user import User
from app.schemas.image_generation import (
    GeneratedImageItem,
    ImageGenerateRequest,
    ImageGenerateResponse,
)
from app.services.attachment_service import AttachmentService
from app.services.chat_service import ChatService
from app.services.image_generation_service import ImageGenerationService


router = APIRouter(prefix="/api/generate-image", tags=["image-generation"])


@router.post("", response_model=ImageGenerateResponse)
async def generate_image(
    request: ImageGenerateRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    thread = await ChatService.get_thread(db, current_user.id, request.chat_thread_id)
    if not thread:
        raise HTTPException(status_code=404, detail="Thread not found")

    generated = await ImageGenerationService.generate_images(
        user_key=str(current_user.id),
        prompt=request.prompt,
        num_images=request.num_images,
        aspect_ratio=request.aspect_ratio or settings.IMAGE_GEN_DEFAULT_ASPECT_RATIO,
        negative_prompt=request.negative_prompt,
        enhance_prompt=request.enhance_prompt,
    )

    created_attachments = []
    for item in generated:
        attachment = await AttachmentService.create_generated_image_attachment(
            db,
            current_user,
            thread.id,
            item.bytes_data,
            item.mime_type,
            prompt=item.prompt_used,
            model_version=item.model_version,
            aspect_ratio=request.aspect_ratio,
            auto_commit=False,
        )
        created_attachments.append(attachment)

    # Ensure autogenerated IDs exist before building the response schema.
    if created_attachments:
        await db.flush()

    output_items: list[GeneratedImageItem] = []
    for attachment in created_attachments:
        output_items.append(
            GeneratedImageItem(
                url=f"/api/attachments/{attachment.id}/download",
                attachment_id=attachment.id,
                metadata=attachment.metadata_json or {},
            )
        )

    if output_items:
        await db.commit()

    try:
        await AttachmentService.cleanup_expired_generated_images(
            db,
            current_user,
            settings.IMAGE_RETENTION_DAYS,
        )
    except Exception:
        await db.rollback()

    return ImageGenerateResponse(images=output_items, generated_at=datetime.utcnow())
